#define NEWLINE                          1
#define GEO_VERTEX                       2
#define TEXTURE_COORD                    3
#define VERTEX_NORMAL                    4
#define POLY_FACE                        5
#define NAMED_OBJECT                     6
#define OBJECT_NAME                      7
#define NATURAL                          8
#define SLASH                            9
#define NUMBER                          10
#define PARAM_SPACE_VERTICES            11
#define LINE_ELEMENT                    12
