os:
  - linux
  - osx
dist: xenial
sudo: false

language: c
compiler:
  - gcc
  - clang

# Add Ubuntu deps
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - clang-3.9
      - libsdl2-dev
      - libcmocka-dev
      - doxygen
  homebrew:
    update: true
    packages:
      - sdl2
      - cmocka
      - cmake
      - doxygen

matrix:
  exclude:
    # Only test MacOS with clang
    - os: osx
      compiler: gcc

env:
  - CONFIG=Release

install:
  - if [[ $TRAVIS_OS_NAME = osx ]]; then
      export CMAKE=cmake;
      export CTEST=ctest;
      export CPACK=cpack;
      export CC=clang;
      export CMAKE_OPTS=("-G" "Unix Makefiles");
    fi
  - if [[ $TRAVIS_OS_NAME = linux ]]; then
      mkdir /tmp/cmake/ && pushd /tmp/cmake/;
      cd /tmp/cmake/;
      wget https://github.com/Kitware/CMake/releases/download/v3.13.3/cmake-3.13.3-Linux-x86_64.tar.gz;
      tar -xzf cmake-3.13.3-Linux-x86_64.tar.gz cmake-3.13.3-Linux-x86_64/;
      export CMAKE=$PWD/cmake-3.13.3-Linux-x86_64/bin/cmake;
      export CTEST=$PWD/cmake-3.13.3-Linux-x86_64/bin/ctest;
      export CPACK=$PWD/cmake-3.13.3-Linux-x86_64/bin/cpack;
      if [[ $CC_FOR_BUILD = clang ]]; then
        export CC=clang-3.9;
      else
        export CC=gcc-8;
      fi
      export CMAKE_OPTS=("-G" "Unix Makefiles");
      popd;
    fi

script:
  - echo "Starting build process"
  - uname -a
  - $CMAKE --version
  - $CC --version
  - mkdir build && cd build
  - $CMAKE .. -DCMAKE_BUILD_TYPE=$CONFIG -DBUILD_TESTING=ON "${CMAKE_OPTS[@]}"
  - $CMAKE --build . --parallel
  - $CTEST --output-on-failure
  - $CMAKE --build . --target docs --parallel
  - $CMAKE --build . --target ldoc --parallel
