os:
  - linux
  - osx
  - windows
dist: xenial
sudo: false

language: c

# Add Ubuntu deps
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - clang-3.9
      - libsdl2-dev
      - libcmocka-dev
      - doxygen
  homebrew:
    update: true
    packages:
      - sdl2
      - cmocka
      - cmake
      - doxygen

env: REMOVE=1

matrix:
  include:
    - os: osx
      compiler: clang
      env:
        - CONFIG=Release
        - 'CMAKE_OPTS=("-G" "Unix Makefiles")'

    - os: linux
      compiler: clang-3.9
      env:
        - CONFIG=Release
        - 'CMAKE_OPTS=("-G" "Unix Makefiles")'

    - os: linux
      compiler: gcc-8
      env:
        - CONFIG=Release
        - 'CMAKE_OPTS=("-G" "Unix Makefiles")'

 #    - os: windows
 #      compiler: gcc
 #      env:
 #        - CONFIG=Release
 #        - 'CMAKE_OPTS=("-G" "MinGW Makefiles" "-DCMAKE_SH=CMAKE_SH-NOTFOUND")'
  exclude:
    env: REMOVE=1

before_install:
  - bash --version

# installing dependencies and setting up environment
install:
  - if [[ $TRAVIS_OS_NAME = osx ]]; then
      export CMAKE=cmake;
      export CTEST=ctest;
      export CPACK=cpack;
    fi
  - if [[ $TRAVIS_OS_NAME = linux ]]; then
      mkdir /tmp/cmake/ || exit 1;
      pushd /tmp/cmake/ || exit 1;
      echo "Installing CMake 3.13";
      wget https://github.com/Kitware/CMake/releases/download/v3.13.3/cmake-3.13.3-Linux-x86_64.tar.gz;
      tar -xzf cmake-3.13.3-Linux-x86_64.tar.gz cmake-3.13.3-Linux-x86_64/;
      export CMAKE=/tmp/cmake/cmake-3.13.3-Linux-x86_64/bin/cmake;
      export CTEST=/tmp/cmake/cmake-3.13.3-Linux-x86_64/bin/ctest;
      export CPACK=/tmp/cmake/cmake-3.13.3-Linux-x86_64/bin/cpack;
      popd || exit 1;
    fi
  - if [[ $TRAVIS_OS_NAME = windows ]]; then
      echo "Installing 7zip";
      choco install 7zip.portable;

      echo "Installing CMake";
      mkdir /tmp/cmake/;
      pushd /tmp/cmake/ || exit 1;
      wget https://github.com/Kitware/CMake/releases/download/v3.14.0-rc1/cmake-3.14.0-rc1-win64-x64.zip;
      7z e -y cmake-3.14.0-rc1-win64-x64.zip;
      ls -lt;
      export CMAKE="$PWD/cmake-3.14.0-rc1-win64-x64/bin/cmake.exe";
      export CTEST="$PWD/cmake-3.14.0-rc1-win64-x64/bin/ctest.exe";
      export CPACK="$PWD/cmake-3.14.0-rc1-win64-x64/bin/cpack.exe";
      echo "CMAKE = ${CMAKE}";
      popd;

      echo "Installing SDL2";
      mkdir /tmp/sdl2/;
      pushd /tmp/sdl2/ || exit 1;
      wget https://www.libsdl.org/release/SDL2-devel-2.0.9-mingw.tar.gz;
      tar -xzf SDL2-devel-2.0.9-mingw.tar.gz SDL2-2.0.9/;
      SDL2_ROOT="/tmp/sdl2/SDL2-2.0.9/";
      ls -lt;
      popd;

      echo "Installing cmocka";
      mkdir /tmp/cmocka/;
      pushd /tmp/cmocka/ || exit 1;
      wget https://cmocka.org/files/1.1/cmocka-1.1.3.tar.xz;
      ls -lt;
      7z e -y cmocka-1.1.3.tar.xz && 7z x -y cmocka-1.1.3.tar;
      ls -lt;
      cd cmocka-1.1.3/ || exit 1;
      mkdir build || exit 1;
      cd build || exit 1;
      $CMAKE .. -DCMAKE_BUILD_TYPE=$CONFIG
                -DCMAKE_INSTALL_PREFIX=/tmp/cmocka/install/
                -G "MinGW Makefiles" -DCMAKE_SH=CMAKE_SH-NOTFOUND;
      $CMAKE --build . --parallel;
      $CMAKE --build . --target install;
      CMOCKA_ROOT="/tmp/cmocka/install/";
      popd;
      CMAKE_OPTS+=("-DCMAKE_PREFIX_PATH=$SDL2_ROOT;$CMOCKA_ROOT");
    fi

script:
  - echo "Starting build process"
  - uname -a
  - $CMAKE --version
  - $CC --version
  - mkdir build && cd build
  - $CMAKE .. -DCMAKE_BUILD_TYPE=$CONFIG -DBUILD_TESTING=ON "${CMAKE_OPTS[@]}"
  - $CMAKE --build . --parallel
  - $CTEST --output-on-failure
  - $CMAKE --build . --target docs --parallel
  - $CMAKE --build . --target ldoc --parallel
