os:
  - linux
  - osx
dist: xenial
sudo: false

language: c
compiler:
  - gcc-8
  - clang-3.9
  - clang

# Add Ubuntu deps
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - clang-3.9
      - libsdl2-dev
      - libcmocka-dev
  homebrew:
    packages:
      - sdl2
      - cmocka
      - cmake

matrix:
  exclude:
    - os: osx
      compiler: gcc-8
    - os: osx
      compiler: clang-3.9
    - os: linux
      compiler: clang

env:
  - CONFIG=Release

install:
  - if [[ $TRAVIS_OS_NAME = osx ]]; then
      export CMAKE=cmake;
      export CTEST=ctest;
    fi
  - if [[ $TRAVIS_OS_NAME = linux ]]; then
      wget https://github.com/Kitware/CMake/releases/download/v3.13.3/cmake-3.13.3-Linux-x86_64.tar.gz;
      tar -xzf cmake-3.13.3-Linux-x86_64.tar.gz cmake-3.13.3-Linux-x86_64/;
      export CMAKE=$PWD/cmake-3.13.3-Linux-x86_64/bin/cmake;
      export CTEST=$PWD/cmake-3.13.3-Linux-x86_64/bin/ctest;
    fi

script:
  - echo "Starting build process"
  - uname -a
  - $CMAKE --version
  - $CC --version
  - mkdir build && cd build
  - $CMAKE .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=$CONFIG -DBUILD_TESTING=ON
  - $CMAKE --build . --parallel
  - $CTEST --output-on-failure
